### ISSUE TITLE
Path multiple slashes 

### ISSUE THREAD

**Issue by giper45** [jonschlinkert/is-valid-path#1]
maree///eafwimeeioam  gives valid path . Is it correct ?

**Comment by jonschlinkert** [comment]
since that would just get normalized by `path.normalize()`, it should be fine.  for example:

```js
var path = require('path');
console.log(path.normalize('foo////////////////////bar'));
```

**Comment by giper45** [comment]
Thank I just used this :) , now I normalize the path even if the user sent foo///bar -> foo/bar . Thanks !

**Comment by jonschlinkert** [comment]
no problem, happy to help!
